name: build-arduino
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-board-fqbn:
        - arduino:avr:uno
        - esp8266:esp8266:nodemcuv2
        - esp32:esp32:esp32thing
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Arduino build
      uses: ArminJo/arduino-test-compile@v3
      with:
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json
         arduino-board-fqbn: ${{ matrix. arduino-board-fqbn }}